### ISSUE TITLE
change the currency

### ISSUE THREAD

**Issue by georgesuba** [softwareguru/stripe-pay#1]
Hi, first of all thanks for this nice app. I would like to ask how to change currency on this app. I've done it on form however when testing in popup window the blue button keeps saying PAY US $.. Ive setup currency in files to gbp but still nothing changed. Can you advice please? Thanks.

**Comment by pedrogk** [comment]
According to API documentation (https://stripe.com/docs/charges), all you should need to do is change the currency. Need to use the 3 letter code in lower case (https://stripe.com/docs/currencies).  So, I suppose that what you would need to do is simply edit charge.php and change line 41 to: 
``"currency" => "gbp",``

note: my code currently uses single quotes ('usd') but I see that the docs have double quote, so I don't know if that could affect. From what I remember, php treats single and double quotes the same, but just to be safe try the double quotes.

Let me know if it works. If not, I will have time to check this out properly until the weekend.

**Comment by georgesuba** [comment]
Hi, yeh I modified last night charge.php and config.php accordingly and got it working. Thanks
